### PR TITLE
shfmt: Add support for -ci and -s

### PR DESCRIPTION
**Pull request by ambakshi**

### CODE REVIEW

**Review by pecigonzalo — CHANGES_REQUESTED** [review]
@ambakshi Nice addition, would you think it makes sense to put the `--indentation` in the same `args` format?

**Comment by ambakshi** [comment]
Hi pecigonzalo, Yes that totally makes sense I just wanted to keep the amount of change to a minimum. Will fix and resubmit.

Thanks,
Amit

**Comment by eggplants** [comment]
@ambakshi ping

**Comment by pecigonzalo** [comment]
This is no longer required as we now use `shfmt` directly. Thanks for the PR and sorry I took so long to action this.

**Pull request closed without merging**
